name: Preview Release

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'packages/**'
      - 'package.json'
      - 'yarn.lock'
      - '.github/workflows/preview-release.yml'

jobs:
  preview-release:
    name: Publish Preview Packages
    runs-on: ubuntu-latest
    # Only run on pull requests from the same repository (not forks)
    if: github.event.pull_request.head.repo.full_name == github.repository
    permissions:
      contents: read
      pull-requests: write
      id-token: write  # Required for provenance
    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build packages
        run: yarn build:packages

      - name: Publish preview packages
        run: |
          npx pkg-pr-new publish \
            './packages/account-sdk' \
            './packages/account-ui' \
            --compact \
            --comment=update \
            --template='stackblitz'
