name: Release Please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      account--release_created: ${{ steps.release.outputs['packages/account-sdk--release_created'] }}
      account-ui--release_created: ${{ steps.release.outputs['packages/account-ui--release_created'] }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  publish-account:
    needs: release-please
    if: ${{ needs.release-please.outputs.account--release_created == 'true' }}
    name: Publish @base-org/account
    runs-on: ubuntu-latest
    environment: publish
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup
        uses: ./.github/actions/setup

      - name: Update npm
        run: npm install -g npm@latest

      - name: Prebuild Packages
        run: yarn workspace @base-org/account prebuild

      - name: Build Packages
        run: yarn workspace @base-org/account build

      - name: Publish to npm
        run: |
          cd packages/account-sdk
          npm publish --tag latest --access public

  publish-account-ui:
    needs: release-please
    if: ${{ needs.release-please.outputs.account-ui--release_created == 'true' }}
    name: Publish @base-org/account-ui
    runs-on: ubuntu-latest
    environment: publish
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup
        uses: ./.github/actions/setup

      - name: Update npm
        run: npm install -g npm@latest

      - name: Build Packages
        run: yarn build:packages

      - name: Publish to npm
        run: |
          cd packages/account-ui
          npm publish --tag latest --access public
