name: Release Account UI

on:
  workflow_dispatch:
    inputs:
      packageVersion:
        description: "The version to publish in MAJOR.MINOR.PATCH format"
        required: true
        default: ""

jobs:
  release:
    env:
      PACKAGE_VERSION: ${{ github.event.inputs.packageVersion }}
    name: Release
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: 'Setup'
        uses: ./.github/actions/setup

      - name: Set version
        run: yarn workspace @base-org/account-ui version ${{ env.PACKAGE_VERSION }}

      - name: Build Packages
        run: yarn build:packages

      # Publish to npm
      - name: Set up npm auth
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm
        run: |
          cd packages/account-sdk
          npm publish --tag latest --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
